updateaudiovid2vid

diff --git a/media-tools/audiovid2vid b/media-tools/audiovid2vid
--- a/media-tools/audiovid2vid
+++ b/media-tools/audiovid2vid
@@ -2,61 +2,223 @@
 #
 # SPDX-License-Identifier: AGPL-3.0
 
+_bin="$( \
+  dirname \
+    "$( \
+      command \
+        -v \
+	  "env")")"
+_lib="${_bin}/../lib"
+_share="${_bin}/../share"
+source \
+  "${_lib}/libcrash-bash/crash-bash"
+
+# Check all required programs
+# are available
+_requirements() {
+  _check_cmd \
+    "ffmpeg"
+}
+
+# shellcheck disable=SC2034
+_global_variables() {
+  out_video=""
+  in_audio=""
+  in_videos=()
+  video_encode=""
+  out_stdout=""
+  color=""
+  quiet=""
+}
+
+_ffmpeg_options_load() {
+  local \
+    ffmpeg_options
+  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
+  [ -e "${ffmpeg_options}" ] && \
+    source \
+      "${ffmpeg_options}" || \
+  true
+}
+
 # Merges sound with a sequence of vids
 # $1: output file
 # $2: sound file
 # $@: videos
 _audiovid2vid() {
   local \
-    _out="${1}" \
+    _out=(
+      "${1}"
+    ) \
     _aud="${2}" \
-    _pics=() \
-    _ffmpeg_opts=() \
-    _tmp
+    _vids=() \
+    _opts=() 
   shift \
     2
-  _pics=(
-    "${@}"
+  _vids=(
+    "$@"
   )
-  _tmp="$( \
-    mktemp \
-      -d)"
-  _ffmpeg_opts=(
+  _msg_info \
+    "input videos: ${_vids[*]}"
+  _opts+=(
+    "${_ffmpeg_opts[@]}"
     # -loop 1
     -i "${_vids[@]}"
     -i "${_aud}"
-    -c:v libx264
+  )
+  [[ "$(_get \
+	  "video" \
+	  "encode")" == "y" ]] && \
+    _x265="true" && \
+    _opts+=(
+      -c:v libx265
+      -pix_fmt yuv420p
+  )
+  [[ "$(_get \
+	  "video" \
+	  "encode")" == "n" ]] && \
+    _opts+=(
+      -c:v copy
+  )
+  _opts+=(
     -c:a aac
     -b:a 48k
-    -pix_fmt yuv420p
     -shortest
   )
+  if [[ "${_out[*]}" == "" ]] || \
+     [[ "$(_get \
+             "out" \
+	     "stdout")" == "y" ]]; then
+    _out+=(
+      -
+    )
+  fi
   ffmpeg \
-    "${_ffmpeg_opts[@]}" \
-    "${_out}"
+    "${_opts[@]}" \
+    "${_out[*]}"
 }
 
+# Set defaults and, if present, overrides
+# from arch-grub command line option parameters
+_set_overrides() {
+  _set_override \
+    "video" \
+    "encode" \
+    "n"
+  _set_override \
+    "out" \
+    "stdout" \
+    "n"
+  if [[ -v override_color ]]; then
+    color="${override_color}"
+  elif [[ -z "${color}" ]]; then
+    color="n"
+  fi
+  if [[ -v override_quiet ]]; then
+    quiet="${override_quiet}"
+  elif [[ -z "${quiet}" ]]; then
+    quiet="y"
+  fi
+}
+
+# Show help usage, with an exit status.
+# $1: exit status number.
 _usage() {
   local \
-    _exit_code="${1}"
-  echo \
-    "Usage: audiovid2vid <output_video> <input_audio> [input_video]"
+    _usage_text
+  IFS='' \
+    read \
+      -r \
+      -d '' \
+      _usage_text << \
+        ENDUSAGETEXT || true
+
+Cut media files
+
+Usage:
+  $(_get "app" "name")
+    [options]
+    <output_video>
+    <input_audio>
+    [input_video]
+  options:
+     -e                   Whether to encode the resulting video
+                          or use encoder from input media.
+			  Default: $(_get "video" "encode")
+     -s                   Output to stdout.
+			  Default: $(_get "out" "stdout")
+     -h                   This message.
+     -v                   Enable verbose output
+ENDUSAGETEXT
+  _printf \
+    '%s\n' \
+    "${_usage_text}"
   exit \
-    "${_exit_code}"
+    "${1}"
 }
 
+_globals
+_global_variables
+_requirements
+# shellcheck disable=SC2004
+# shellcheck disable=SC2034
+while \
+  getopts \
+    'scevh?' \
+    arg; do
+  case \
+    "${arg}" in
+    s) override_out_stdout="y" ;;
+    c) override_color="y" ;;
+    e) override_video_encode="y" ;;
+    v) override_quiet="n" ;;
+    h|?) _set_overrides && \
+	 _usage \
+           0 ;;
+    *)
+    _msg_error \
+      "Invalid argument '${arg}'" \
+      0 && \
+    _set_overrides && \
+    _usage \
+      1
+    ;;
+  esac
+done
+shift \
+  $(( \
+    OPTIND - 1 \
+  ))
+
 (( $# < 3 )) && \
+  _set_overrides && \
   _usage \
     1
-
-_out="${1}"
-_aud="${2}"
-shift 2
-_vids=(
-  "${@}"
+_set \
+  "out" \
+  "video" \
+  "${1}"
+_set \
+  "in" \
+  "audio" \
+  "${2}"
+shift \
+  2
+echo "$@"
+in_videos=(
+  "$@"
 )
-
+echo \
+  "${in_videos[@]}"
+_set_overrides
+_config_user_init \
+  "media-tools"
+_ffmpeg_options_load
 _audiovid2vid \
-  "${_out}" \
-  "${_aud}" \
-  "${_vids[@]}"
+  "$(_get \
+       "out" \
+       "video")" \
+  "$(_get \
+       "in" \
+       "audio")" \
+  "${in_videos[@]}"
