fix blackvid (vid)

diff --git a/media-tools/blackvid b/media-tools/blackvid
--- a/media-tools/blackvid
+++ b/media-tools/blackvid
@@ -2,110 +2,176 @@
 #
 # SPDX-License-Identifier: AGPL-3.0
 
-_path="$( \
-  export \
-    _OLDPWD="$(pwd)" && \
-  cd \
-    "$(dirname \
-         "${BASH_SOURCE[0]}")" && \
-  echo \
-    "$(pwd)" && \
-  cd "${_OLDPWD}")"
+_bin="$( \
+  dirname \
+    "$( \
+      command \
+        -v \
+	  "env")")"
+_lib="${_bin}/../lib"
+_share="${_bin}/../share"
+source \
+  "${_lib}/libcrash-bash/crash-bash"
 
-app_name="$( \
-  basename \
-    "${BASH_SOURCE[0]}")"
+# shellcheck disable=SC2034
+_global_variables() {
+  in_file=""
+  vid_duration=""
+  color=""
+  quiet=""
+}
+
+# Check all required programs
+# are available
+_requirements() {
+  _check_cmd \
+    "ffmpeg"
+}
+
+
+export _in="fullnm.mp4" _seconds="$(scale=5; echo 7.5 | bc)" _audio_in="../Music/pr.m4a" _in_endcut="40" _audio_endcut="42" _video_out="prfm.mp4" _black_outro="3" && echo "${_seconds}" && ffmpeg -i "${_in}" -vf "trim=0:${_seconds},geq=0:128:128" -af "atrim=0:${_seconds},volume=0" -video_track_timescale 600 "b${_seconds}.mp4" -y && ffmpeg -i "${_in}" -vf "trim=0:${_black_outro},geq=0:128:128" -af "atrim=0:${_black_outro},volume=0" -video_track_timescale 600 "bo${_black_outro}.mp4" && ffmpeg -i "${_in}" -c copy -video_track_timescale 600 "${_in}.600.mp4" -y && bash  ~/media-tools/media-tools/vidcat "edit.mp4" "b${_seconds}.mp4" "${_in}.600.mp4" &&  bash ~/media-tools/media-tools/mediacut "edit.mp4" 0 "${_in_endcut}" "edit.cut.mp4" && bash ~/media-tools/media-tools/vidcat "edit.bo.mp4" "edit.cut.mp4" "bo${_black_outro}.mp4" && bash ~/media-tools/media-tools/audiovid2vid "${_video_out}" "${_audio_in}" "edit.bo.mp4"
+_ffmpeg_options_load() {
+  local \
+    ffmpeg_options
+  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
+  [ -e "${ffmpeg_options}" ] && \
+    source \
+      "${ffmpeg_options}" || \
+  true
+}
 
 # Create blank video of given length;
 # output file must have mpeg extension
-# $1: output video file
-# $2: length of resulting blank file
-# $@: input video files to infer best
-#     size (sorted)
+# $1: input video files to infer size
+# $2: output video file
+# $3: length of resulting blank file
 _blackvid() {
   local \
-    _out="${1}" \
-    _len="${2}" \
-    _cmd="_ffmpeg_adapta" \
-    _i=0 \
-    _in=() \
-    _af="" \
-    _vf="" \
-    _vids=()
-  shift 2
-  _in=("$@")
-  [[ "${_in[@]}" == "" ]] && \
-    _cmd=_ffmpeg
-  "${_cmd}"
-}
-
-_ffmpeg() {
+    _in="${1}" \
+    _out="${2}" \
+    _length="${3}" \
+    _opts=()
+  _opts+=(
+    "${_ffmpeg_opts[@]}"
+    -vf
+      "trim=0:${_length},geq=0:128:128"
+    -af
+      "atrim=0:${_length},volume=0"
+    -video_track_timescale
+      600
+  )
   ffmpeg \
-    -y \
-    -t "${_len}" \
-    -s 640x480 \
-    -f rawvideo \
-    -pix_fmt rgb24 \
-    -r 25 \
-    -i /dev/zero \
-    "${_out}.mpeg"
-
-  
-  ffmpeg \
-    -y \
-    -i "${_out}.mpeg" \
-    "${_out}.webm"
-
-  # ffmpeg \
-  #   -y \
-  #   -i "${_out}.webm" \
-  #   -preset \
-  #   -f mp4 \
-  #   "${_out}.mp4"
-
-  # ffmpeg \
-  #   -y \
-  #   -f lavfi \
-  #   -i anullsrc \
-  #   -i "${_out}.webm" \
-  #   -c:v copy \
-  #   -c:a ac3 \
-  #   -map 0:a \
-  #   -map 1:v \
-  #   -shortest \
-  #   "${_out}"
-  # rm "${_out}.mpeg"
-}
-
-_ffmpeg_adapta() {
-  rm "${_out}.queue"
-  for _vid in "${_in[@]}"; do
-    echo \
-      "file '$(realpath \
-                 ${_vid})'" >> \
-      "${_out}.queue"
-  done
-  _af="atrim=0:${_len},volume=0"
-  _vf="trim=0:${_len},geq=0:128:128"
-  ffmpeg \
-    -safe 0 \
-    -i "${_out}.queue" \ # ${_vids[@]} \
-    -vf "${_vf}" \
-    -af "${_af}" \
-    -video_track_timescale 600 \
+    -i \
+      "${_in}" \
+    "${_ffmpeg_opts[@]}" \
     "${_out}"
 }
 
-_msg_err() {
-  local \
-    _msg=("$@") \
-    _line
-  for _line in "${_msg[@]}"; do
-    echo "${_line}"
-  done
-  exit 1
+_set_overrides() {
+  if [[ -v override_color ]]; then
+    color="${override_color}"
+  elif [[ -z "${color}" ]]; then
+    color="n"
+  fi
+  if [[ -v override_quiet ]]; then
+    quiet="${override_quiet}"
+  elif [[ -z "${quiet}" ]]; then
+    quiet="y"
+  fi
 }
 
+# Show help usage, with an exit status.
+# $1: exit status number.
+_usage() {
+  local \
+    _usage_text
+  IFS='' \
+    read \
+      -r \
+      -d '' \
+      _usage_text << \
+        ENDUSAGETEXT || true
+Generates a black mute video of given length from a input video
+
+Usage:
+  $(_get "app" "name")
+    [options]
+    <input_file>
+    <output_file>
+    <length>
+  options:
+     -h                   This message.
+     -v                   Enable verbose output
+ENDUSAGETEXT
+  _printf \
+    '%s\n' \
+    "${_usage_text}"
+  exit \
+    "${1}"
+}
+
+_globals
+_global_variables
+_requirements
+# shellcheck disable=SC2004
+# shellcheck disable=SC2034
+while \
+  getopts \
+    'm:cvh?' \
+    arg; do
+  case \
+    "${arg}" in
+    m) override_encode_mode="${OPTARG}" ;;
+    c) override_color="y" ;;
+    v) override_quiet="n" ;;
+    h|?) _set_overrides && \
+         _usage \
+           0 ;;
+    *)
+    _msg_error \
+      "Invalid argument '${arg}'" \
+      0
+    _usage \
+      1
+    ;;
+  esac
+done
+shift \
+  $(( \
+    OPTIND - 1 \
+  ))
+(( ${#} < 3 )) && \
+  _usage \
+    1
+_set \
+  "in" \
+  "file" \
+  "${1}"
+_set \
+  "out" \
+  "file" \
+  "${2}"
+_set \
+  "vid" \
+  "length" \
+  "${3}"
+_set_overrides
+_config_user_init \
+  "media-tools"
+_ffmpeg_options_load
+_ytencode \
+  "$( \
+    _get \
+      "in" \
+      "file")" \
+  "$( \
+    _get \
+      "out" \
+      "file")" \
+  "$( \
+    _get \
+      "encode" \
+      "mode")"
 _out="${1}"
 _len="${2}"
 
