update vidcut

diff --git a/media-tools/vidcut b/media-tools/vidcut
--- a/media-tools/vidcut
+++ b/media-tools/vidcut
@@ -2,106 +2,34 @@
 #
 # SPDX-License-Identifier: AGPL-3.0
 
-_globals() {
-  local \
-    _OLDPWD
-  set \
-    -e \
-    -u
-  shopt \
-    -s \
-      extglob
-  # Control the environment
-  umask \
-    0022
-  export \
-    LC_ALL="C.UTF-8"
-  # LC_ALL=C.UTF-8, unlike LC_ALL=C,
-  # does not override LANGUAGE.
-  # See 
-  # https://sourceware.org/bugzilla/show_bug.cgi?id=16621
-  # and 
-  # https://savannah.gnu.org/bugs/?62815
-  [[ -v LANGUAGE ]] && \
-    unset \
-      LANGUAGE
-  [[ -v SOURCE_DATE_EPOCH ]] || \
-    printf \
-      -v \
-        SOURCE_DATE_EPOCH \
-      '%(%s)T' \
-      -1
-  export \
-    SOURCE_DATE_EPOCH
-  
-  # Get script path
-  # shellcheck disable=SC2005
-  _path="$( \
-    _OLDPWD="$( \
-      pwd)" && \
-    export \
-      _OLDPWD && \
-    cd \
-      "$( \
-	dirname \
-          "${BASH_SOURCE[0]}")" && \
-    echo \
-      "$(pwd)" && \
-    cd \
-      "${_OLDPWD}" && \
-    unset \
-      _OLDPWD)"
-  unset \
-    _OLDPWD
-  # Set application name
-  # from the script's file name
-  app_name="${0##*/}"
+_bin="$( \
+  dirname \
+    "$( \
+      command \
+        -v \
+	  "env")")"
+_lib="${_bin}/../lib"
+_share="${_bin}/../share"
+source \
+  "${_lib}/libcrash-bash/crash-bash"
+
+# Check all required programs
+# are available
+_requirements() {
+  true
 }
+
 
 # shellcheck disable=SC2034
 _global_variables() {
+  out_stdout=""
   in_file=""
+  cut_start=""
+  cut_length=""
   out_file=""
   color=""
   quiet=""
 }
-
-# Show an INFO message
-# $1: message string
-_msg_info() {
-  local \
-    _msg=(
-      "$@"
-    ) \
-    _fmt_line=() \
-    _line
-  [[ "${quiet}" == "y" ]] || \
-    for _line \
-      in "${_msg[@]}"; do
-      _printf \
-        '[%s] INFO: %s\n' \
-        "${app_name}" \
-        "${_line}"
-    done
-}
-
-# Show a WARNING message
-# $1: message string
-_msg_warning() {
-  local \
-    _msg=()
-  _msg=(
-    "${1}"
-  )
-  _printf \
-    '[%s] WARNING: %s\n' \
-    "${app_name}" \
-    "${_msg[*]}" >&2
-}
-
-
-app_name="$(basename \
-	      "${BASH_SOURCE[0]}")"
 
 # Cut video from A to B
 # $1: output video file
@@ -109,46 +37,114 @@ app_name="$(basename \
 # $3: time to cut in (in seconds)
 # $4: input video file
 _vidcut() {
-
   local \
     _in="${1}" \
     _start="${2}" \
-    _end="${3}" \
-    _out="${4}"
+    _length="${3}" \
+    _out=(
+      "${4}"
+    )
+  if [[ "${_out[*]}" == "" ]] || \
+     [[ "$(_get \
+             "out" \
+	     "stdout")" == "y" ]]; then
+    _out+=(
+      -
+    )
+  fi
+  if [[ "${_out[*]}" != "" ]] && \
+     [[ "$(_get \
+             "out" \
+	     "stdout")" == "n" ]]; then
+    _out+=(
+      "${4}"
+    )
+  fi
   ffmpeg \
     -ss "${_start}" \
     -i "${_in}" \
-    -to "${_end}" \
+    -to "${_length}" \
     -reset_timestamps 1 \
     -map 0 \
     -c copy \
-    "${_out}"
-
+    "${_out[*]}"
 }
 
+# Set defaults and, if present, overrides
+# from arch-grub command line option parameters
+_set_overrides() {
+  _set_override \
+    "out" \
+    "stdout" \
+    "n"
+  if [[ -v override_color ]]; then
+    color="${override_color}"
+  elif [[ -z "${color}" ]]; then
+    color="n"
+  fi
+  if [[ -v override_quiet ]]; then
+    quiet="${override_quiet}"
+  elif [[ -z "${quiet}" ]]; then
+    quiet="y"
+  fi
+}
+
+
+# Show help usage, with an exit status.
+# $1: exit status number.
 _usage() {
   local \
-    _exit_code="${1}"
-  echo \
-    "Usage: vidcut <in> <start> <end> <out>" && \
+    _usage_text
+  IFS='' \
+    read \
+      -r \
+      -d '' \
+      _usage_text << \
+        ENDUSAGETEXT || true
+
+Cut videos
+
+Usage:
+  $(_get "app" "name")
+    [options]
+    <input_file>
+    <cut_start>
+    <cut_length>
+    <output_file>
+  options:
+     -s                   Output to stdout.
+     -h                   This message.
+     -v                   Enable verbose output
+ENDUSAGETEXT
+  _printf \
+    '%s\n' \
+    "${_usage_text}"
   exit \
-    "${_exit_code}"
+    "${1}"
 }
 
+_globals
+_global_variables
+_requirements
+# shellcheck disable=SC2004
+# shellcheck disable=SC2034
 while \
   getopts \
     'cvh?' \
     arg; do
   case \
     "${arg}" in
+    s) override_output_stdout="y" ;;
     c) override_color="y" ;;
     v) override_quiet="n" ;;
-    h|?) _usage \
+    h|?) _set_overrides && \
+	 _usage \
            0 ;;
     *)
     _msg_error \
       "Invalid argument '${arg}'" \
-      0
+      0 && \
+    _set_overrides && \
     _usage \
       1
     ;;
@@ -159,17 +155,21 @@ shift \
     OPTIND - 1 \
   ))
 
-(( $# < 4 )) && \
+(( $# < 3 )) && \
   _usage \
     1
-
-_in="${1}"
-_start="${2}"
-_end="${3}"
-_out="${4}"
-
+(( $# < 3 )) && \
+  _msg_info \
+    "no output file givon, will return to stdout"
+    
+in_file="${1}"
+cut_start="${2}"
+cut_end="${3}"
+(( $# == 4 )) && \
+  out_file="${4}"
+_set_overrides
 _vidcut \
-  "${_in}" \
-  "${_start}" \
-  "${_end}" \
-  "${_out}"
+  "${in_file}" \
+  "${cut_start}" \
+  "${cut_end}" \
+  "${out_file}"
