fix install path

diff --git a/media-tools/vidscale b/media-tools/vidscale
--- a/media-tools/vidscale
+++ b/media-tools/vidscale
@@ -13,6 +13,21 @@ _share="${_bin}/../share"
 source \
   "${_lib}/libcrash-bash/crash-bash"
 
+# shellcheck disable=SC2034
+_global_variables() {
+  input_video=""
+  output_video=""
+  color=""
+  quiet=""
+}
+
+# Check all required programs
+# are available
+_requirements() {
+  true
+}
+
+
 _ffmpeg_options_load() {
   local \
     ffmpeg_options
@@ -55,11 +70,81 @@ _vidscale() {
     "${_out}"
 }
 
+# Set defaults
+_set_overrides() {
+  if [[ -v override_color ]]; then
+    color="${override_color}"
+  elif [[ -z "${color}" ]]; then
+    color="n"
+  fi
+  if [[ -v override_quiet ]]; then
+    quiet="${override_quiet}"
+  elif [[ -z "${quiet}" ]]; then
+    quiet="y"
+  fi
+}
+
+# Show help usage, with an exit status.
+# $1: exit status number.
+_usage() {
+  local \
+    _usage_text
+  IFS='' \
+    read \
+      -r \
+      -d '' \
+      _usage_text << \
+        ENDUSAGETEXT || true
+Scale up or down a video by a factor
+
+Usage:
+  $(_get "app" "name")
+    <input_video>
+    <output_video>
+    <scale>
+  options:
+     -h                   This message.
+     -v                   Enable verbose output
+ENDUSAGETEXT
+  _printf \
+    '%s\n' \
+    "${_usage_text}"
+  exit \
+    "${1}"
+}
+
 _globals
-(( $# < 3 )) && \
-  echo \
-    "Usage: vidscale <in> <out> <scale>" && \
-  exit
+_global_variables
+_requirements
+# shellcheck disable=SC2004
+# shellcheck disable=SC2034
+while \
+  getopts \
+    'cvh?' \
+    arg; do
+  case \
+    "${arg}" in
+    c) override_color="y" ;;
+    v) override_quiet="n" ;;
+    h|?) _set_overrides && \
+         _usage \
+           0 ;;
+    *)
+    _msg_error \
+      "Invalid argument '${arg}'" \
+      0
+    _usage \
+      1
+    ;;
+  esac
+done
+shift \
+  $(( \
+    OPTIND - 1 \
+  ))
+(( ${#} < 3 )) && \
+  _usage \
+    1
 
 _in="${1}"
 _out="${2}"
