add ytbulkencode with simple resuming

diff --git a/media-tools/ytbulkencode b/media-tools/ytbulkencode
--- a/media-tools/ytbulkencode
+++ b/media-tools/ytbulkencode
@@ -12,6 +12,13 @@ _lib="${_bin}/../lib"
 source \
   "${_lib}/libcrash-bash/crash-bash"
 
+# shellcheck disable=SC2034
+_global_variables() {
+  input_directory=""
+  color=""
+  quiet=""
+}
+
 _ytbulkencode() {
   local \
     _dir="${1}" \
@@ -69,16 +76,77 @@ _ytbulkencode() {
   done
 }
 
-_usage() {
-  local \
-    _code="${1}"
-  echo \
-    "Usage: ytbulkencode <dir>"
-  exit \
-    "${_code}"
+# Set defaults
+_set_overrides() {
+  if [[ -v override_color ]]; then
+    color="${override_color}"
+  elif [[ -z "${color}" ]]; then
+    color="n"
+  fi
+  if [[ -v override_quiet ]]; then
+    quiet="${override_quiet}"
+  elif [[ -z "${quiet}" ]]; then
+    quiet="y"
+  fi
 }
 
-(( $# < 1 )) && \
+# Show help usage, with an exit status.
+# $1: exit status number.
+_usage() {
+  local \
+    _usage_text
+  IFS='' \
+    read \
+      -r \
+      -d '' \
+      _usage_text << \
+        ENDUSAGETEXT || true
+Use as systemctl
+
+Usage:
+  $(_get "app" "name")
+    <directory>
+  options:
+     -h                   This message.
+     -v                   Enable verbose output
+ENDUSAGETEXT
+  _printf \
+    '%s\n' \
+    "${_usage_text}"
+  exit \
+    "${1}"
+}
+
+_globals
+_global_variables
+_requirements
+# shellcheck disable=SC2004
+# shellcheck disable=SC2034
+while \
+  getopts \
+    'cvh?' \
+    arg; do
+  case \
+    "${arg}" in
+    c) override_color="y" ;;
+    v) override_quiet="n" ;;
+    h|?) _set_overrides && \
+         _usage \
+           0 ;;
+    *)
+    _msg_error \
+      "Invalid argument '${arg}'" \
+      0
+    _usage \
+      1
+    ;;
+  esac
+done
+shift \
+  $(( \
+    OPTIND - 1 \
+  ))
+(( ${#} < 1 )) && \
   _usage \
     1
 _dir="$( \
