ytencode is nice now; it compresses in 1/4 space at around 1x speed what i give it in input

diff --git a/media-tools/ytencode b/media-tools/ytencode
--- a/media-tools/ytencode
+++ b/media-tools/ytencode
@@ -1,11 +1,354 @@
 #!/usr/bin/env bash
 
+_globals() {
+  local \
+    _OLDPWD
+  set \
+    -e \
+    -u
+  shopt \
+    -s \
+      extglob
+  # Control the environment
+  umask \
+    0022
+  export \
+    LC_ALL="C.UTF-8"
+  # LC_ALL=C.UTF-8, unlike LC_ALL=C,
+  # does not override LANGUAGE.
+  # See 
+  # https://sourceware.org/bugzilla/show_bug.cgi?id=16621
+  # and 
+  # https://savannah.gnu.org/bugs/?62815
+  [[ -v LANGUAGE ]] && \
+    unset \
+      LANGUAGE
+  [[ -v SOURCE_DATE_EPOCH ]] || \
+    printf \
+      -v \
+        SOURCE_DATE_EPOCH \
+      '%(%s)T' \
+      -1
+  export \
+    SOURCE_DATE_EPOCH
+  
+  # Get script path
+  # shellcheck disable=SC2005
+  _path="$( \
+    _OLDPWD="$( \
+      pwd)" && \
+    export \
+      _OLDPWD && \
+    cd \
+      "$( \
+	dirname \
+          "${BASH_SOURCE[0]}")" && \
+    echo \
+      "$(pwd)" && \
+    cd \
+      "${_OLDPWD}" && \
+    unset \
+      _OLDPWD)"
+  unset \
+    _OLDPWD
+  # Set application name
+  # from the script's file name
+  app_name="${0##*/}"
+}
+# shellcheck disable=SC2034
+_global_variables() {
+  in_file=""
+  out_file=""
+  color=""
+  quiet=""
+}
+
+# Show an INFO message
+# $1: message string
+_msg_info() {
+  local \
+    _msg=(
+      "$@"
+    ) \
+    _fmt_line=() \
+    _line
+  [[ "${quiet}" == "y" ]] || \
+    for _line \
+      in "${_msg[@]}"; do
+      _printf \
+        '[%s] INFO: %s\n' \
+        "${app_name}" \
+        "${_line}"
+    done
+}
+
+# Show a WARNING message
+# $1: message string
+_msg_warning() {
+  local \
+    _msg=()
+  _msg=(
+    "${1}"
+  )
+  _printf \
+    '[%s] WARNING: %s\n' \
+    "${app_name}" \
+    "${_msg[*]}" >&2
+}
+
+# Show an ERROR message then exit with status
+# $1: message string
+# $2: exit code number (with 0 does not exit)
+_msg_error() {
+  local \
+    _msg=(
+      "${1}"
+    ) \
+    _error=${2}
+  _printf \
+    '[%s] ERROR: %s\n' \
+    "${app_name}" \
+    "${_msg[*]}" >&2
+  if (( _error > 0 )); then
+    exit "${_error}"
+  fi
+}
+
+# Sets object string attributes
+# $1: object
+# $2: an object string attribute
+# $3: a value
+_set() {
+  local \
+    _obj="${1}" \
+    _var="${2}" \
+    _value="${3}" \
+    _target \
+    _ass_target \
+    _ass_type
+  _target="${_obj}_${_var}"
+  _ass_target="${_obj}[${_var}]"
+  _ass_type="$( \
+    _get_type \
+      "${_obj}")"
+  [[ "${_ass_type}" == "dict" ]] && \
+    _target="${_ass_target}"
+  printf \
+    -v "${_target}" \
+    "%s" \
+    "${_value}"
+}
+
+# Returns type ('string', 'list', 'dict') given
+# its name
+# $1: an object
+_get_type() {
+  local \
+    _obj="${1}" \
+    _type="string" \
+    _declare
+  _declare="$( \
+    declare \
+      -p \
+        "${_obj}" 2>&1)"
+  [[ \
+    "${_declare}" == \
+    *"declare:"*"${_obj}"*": not found" ]] && \
+    _type="undefined"
+  [[ \
+    "${_declare}" == \
+    "declare -A "* ]] && \
+    _type="dict"
+  [[ \
+    "${_declare}" == \
+    "typeset -a"* ]] && \
+    _type="array"
+  echo \
+    "${_type}"
+}
+
+# Returns an attribute value for a 
+# given object
+# $1: an object
+# $2: an object attribute
+_get() {
+  local \
+    _obj="${1}" \
+    _var="${2}" \
+    _ass_target \
+    _ass_type \
+    _msg \
+    _ref \
+    _type \
+    _target
+  _ass_target="${_obj}"
+  _target="${_obj}_${_var}"
+  _ref="${_target}[@]"
+  _ass_ref="${_obj}[${_var}]"
+  _type="$( \
+    _get_type \
+      "${_target}")"
+  _ass_type="$( \
+    _get_type \
+      "${_ass_target}")"
+  [[ "${_type}" == "undefined" ]] && \
+  [[ "${_ass_type}" == "undefined" ]] && \
+  [[ ! -v "${_ass_ref}" ]] && \
+    _msg=(
+      "Attribute '${_var}' is not defined"
+      "for object '${_obj}'") && \
+    _msg_error \
+      "${_msg[*]}" \
+      1
+  [[ "${_ass_type}" == "dict" ]] && \
+    if [[ -v "${_ass_ref}" ]]; then
+      _ref="${_ass_ref}"
+    fi
+  printf \
+    "%s\n" \
+    "${!_ref}"
+}
+
+_check_cmd(){
+  local \
+    _cmd="${1}" \
+    _cmd_var \
+    _flag="" \
+    _pkgs=()
+  shift \
+    1
+  _pkgs=(
+    "$@"
+  )
+  _cmd_var="$( \
+    printf \
+      "%s" \
+      "${_cmd}" | \
+      sed \
+        "s/-/_/g")"
+  command \
+     -v \
+     "${_cmd}" &> /dev/null && \
+    printf \
+      -v \
+        "_${_cmd_var}" \
+      "%s" \
+      "$( \
+        command \
+          -v \
+          "${_cmd}")" && \
+    _flag=true
+  [ -e "${_path}/${_cmd}" ] && \
+    printf \
+      -v \
+        "_${_cmd_var}" \
+      "%s" \
+      "${_path}/${_cmd}" && \
+    _flag=true
+  if [[ "${_flag}" != "true" ]]; then
+    if [[ "${_pkgs[*]}" != "" ]]; then
+      _cmd="${_pkgs[*]}"
+    fi
+    _msg_error \
+      "Install ${_cmd}" \
+      1
+  fi
+}
+
+# Reassign an object variable
+# if an override variable is defined;
+# otherwise it defaults
+# to an input default.
+# $1: object
+# $2: variable
+# $3: default value
+_set_override() {
+  local \
+    _obj="${1}" \
+    _var="${2}" \
+    _default="${3}"
+  if [[ -v "override_${_obj}_${_var}" ]]; then
+    _set \
+      "${_obj}" \
+      "${_var}" \
+      "$( \
+        _get \
+	  "override_${_obj}" \
+          "${_var}")"
+  elif [[ -z \
+	    "$( \
+	      _get \
+	        "${_obj}" \
+                "${_var}")" ]]; then
+    _set \
+      "${_obj}" \
+      "${_var}" \
+      "${_default}"
+  fi
+}
+
+# Re-assign an object variable pointing to
+# a path if an override variable is defined,
+# otherwise it defaults to an input path
+# $1: object
+# $2: variable
+# $3: value (a path)
+_override_path() {
+  local \
+    _obj="${1}" \
+    _var="${2}" \
+    _value="${3}" \
+    _path
+  _path="$( \
+    realpath \
+      -q -- \
+      "${_value}" || \
+      true)"
+  [[ "${_path}" == "" ]] && \
+    _msg_error \
+      "${_value} is not a valid path." \
+      1
+  _set_override \
+    "${_obj}" \
+    "${_var}" \
+    "${_value}"
+  _set \
+    "${_obj}" \
+    "${_var}" \
+    "$( \
+      realpath -- \
+        "$( \
+	  _get \
+	    "${_obj}" \
+            "${_var}")")"
+}
+
+# Check all required programs
+# are available
+_requirements() {
+  _check_cmd \
+    "ffmpeg"
+}
+
 _ytencode() {
   local \
     _in="${1}" \
     _out="${2}" \
-    _ffmpeg_opts=()
-  _ffmpeg_opts=(
+    _ffmpeg_opts=() \
+    _loglevel="quiet"
+    _ffmpeg_opts+=(
+    -loglevel
+      "${_loglevel}"
+    )
+  [[ "${quiet}" == "y" ]] && \
+    _ffmpeg_opts+=(
+      -y
+    )
+  [[ "${quiet}" != "y" ]] && \
+    _ffmpeg_opts+=(
+      -stats
+    )
+  _ffmpeg_opts+=(
     -vf
      "yadif,format=yuv420p"
    -force_key_frames
@@ -27,6 +370,7 @@ _ytencode() {
      0
    -movflags
      +faststart
+    -hide_banner
   )
   ffmpeg \
     -i \
@@ -35,21 +379,160 @@ _ytencode() {
     "${_out}"
 }
 
-_in="${1}"
-_out="${2}"
+# Set defaults and, if present, overrides
+# from arch-grub command line option parameters
+_set_overrides() {
+  if [[ -v override_color ]]; then
+    color="${override_color}"
+  elif [[ -z "${color}" ]]; then
+    color="n"
+  fi
+  if [[ -v override_quiet ]]; then
+    quiet="${override_quiet}"
+  elif [[ -z "${quiet}" ]]; then
+    quiet="y"
+  fi
+}
 
+# Show help usage, with an exit status.
+# $1: exit status number.
+_usage() {
+  local \
+    _usage_text
+  IFS='' \
+    read \
+      -r \
+      -d '' \
+      _usage_text << \
+        ENDUSAGETEXT || true
+Convert media file for YouTube consumption
+
+Usage:
+  $(_get "app" "name")
+    [options]
+    <input_file>
+    <output_file>
+  options:
+     -h                   This message.
+     -v                   Enable verbose output
+ENDUSAGETEXT
+  _printf \
+    '%s\n' \
+    "${_usage_text}"
+  exit \
+    "${1}"
+}
+
+# Colorized print
+_printf() {
+  local \
+    _args=()
+    _pygmentize_opts=()
+  _pygmentize_opts=(
+    -g
+    -O style=emacs
+  )
+  _args=(
+      "$@"
+  )
+  # shellcheck disable=SC2059
+  _sho \
+    "$( \
+      printf \
+        "${_args[@]}")" \
+    "${_pygmentize_opts[@]}"
+}
+
+# Colorized Display function
+_sho() {
+  local \
+    _text="${1}" \
+    _pygmentize
+  _pygmentize="$( \
+    command \
+      -v \
+      "pygmentize"{,2} | \
+      head \
+        -n \
+	1)"
+  shift
+  _pygmentize_opts=(
+    "$@"
+  )
+  [[ "${color}" == "y" ]] && \
+  [[ "${_pygmentize}" != "" ]] && \
+    echo \
+      "${_text}" | 
+      "${_pygmentize}" \
+        "${_pygmentize_opts[@]}" && \
+    return
+  printf \
+    "%s\n" \
+    "${_text}"
+}
+
+
+_globals
+_global_variables
+_requirements
+# shellcheck disable=SC2004
+# shellcheck disable=SC2034
+while \
+  getopts \
+    'cvh?' \
+    arg; do
+  case \
+    "${arg}" in
+    c) override_color="y" ;;
+    v) override_quiet="n" ;;
+    h|?) _set_overrides && \
+         _usage \
+           0 ;;
+    *)
+    _msg_error \
+      "Invalid argument '${arg}'" \
+      0
+    _usage \
+      1
+    ;;
+  esac
+done
+shift \
+  $(( \
+    OPTIND - 1 \
+  ))
+(( ${#} < 1 )) && \
+  echo ciao && \
+  _usage \
+    1
+_set \
+  "in" \
+  "file" \
+  "${1}"
 (( $# < 2 )) && \
-  _usage=(
-    "Usage:"
-      "ytencode"
-        "<input_file>"
-	"<output_file>"
-  ) && \
-  echo \
-    "${_usage[*]}" && \
-    exit
-
+  _set \
+    "out" \
+    "file" \
+    "$( \
+      pwd)/$( \
+        basename \
+          "$(_get \
+              "in" \
+              "file")").yt.mp4"
+[[ "$(_get \
+	"out" \
+	"file")" == "" ]] && \
+  _set \
+    "out" \
+    "file" \
+    "${2}"
+_set_overrides
 _ytencode \
-  "${_in}" \
-  "${_out}"
-
+  "$( \
+    _get \
+      "in" \
+      "file")" \
+   "$( \
+    _get \
+      "out" \
+      "file")"
